### ISSUE TITLE
About ScaleNet

### ISSUE THREAD

**Issue by Spritea** [fyangneil/Clustered-Object-Detection-in-Aerial-Image#11]
Nice Work!

The ICCV paper says that there are 2 parts, **CPNet** and **ScaleNet**. It seems that there is only the code about **CPNet** currently. Is that right?

If so, would you share the code about **ScaleNet** in the future? Thanks!

**Comment by fyangneil** [comment]
Yes, you are right. Since i am working at a company, limited time is available to sort the code. Anyway, i will update it ASAP.
