### ISSUE TITLE
The input size format

### ISSUE THREAD

**Issue by Cli98** [fyangneil/Clustered-Object-Detection-in-Aerial-Image#7]
Hi author,

For the input size you specify in paper, what the format? [height * width] or [width * height]

Thank you,

**Comment by ma-siddiqui** [comment]
Hi, 
As per my understanding it is NxCxHxW. Fan - Please confirm.
Thanks,
Siddiqui

**Comment by fyangneil** [comment]
The input size is 1000x600 (WxH) pixels.

**Comment by Cli98** [comment]
Thank you
