### ISSUE TITLE
which solver you use in your paper?

### ISSUE THREAD

**Issue by Cli98** [fyangneil/Clustered-Object-Detection-in-Aerial-Image#8]
Hi author,

Another question. Can you tell me which solver you use in your paper? SGD or Adam?

Many thanks,

**Comment by fyangneil** [comment]
just the default solver in detectron (caffe2 version).

**Comment by fyangneil** [comment]
@Cli98 
just the default solver in detectron (caffe2 version).

**Comment by Cli98** [comment]
Thank you
