### ISSUE TITLE
python version of global_cluster_fusion?

### ISSUE THREAD

**Issue by Cli98** [fyangneil/Clustered-Object-Detection-in-Aerial-Image#9]
Hi Author,

Thank you for your high quality code. Yet I want to ask if you have or plan to upload python version of global_cluster_fusion code? I do not have access to matlab and thus cannot perform global/local fusion.

Thank you

**Comment by fyangneil** [comment]
@Cli98 
Sorry, currently we do not have the python version of global cluster fusion code.

**Comment by Cli98** [comment]
> @Cli98
> Sorry, currently we do not have the python version of global cluster fusion code.

Thank you! I will try to build a python version instead.
